-- AlterTable
ALTER TABLE "loyalty_programs" ADD COLUMN     "backgroundColor" TEXT DEFAULT '#f8f9fa',
ADD COLUMN     "backgroundColorGradient" BOOLEAN DEFAULT false,
ADD COLUMN     "backgroundGradientColors" JSONB,
ADD COLUMN     "backgroundGradientDirection" TEXT DEFAULT 'to right',
ADD COLUMN     "backgroundImage" TEXT,
ADD COLUMN     "bannerUrl" TEXT,
ADD COLUMN     "cardBackgroundColor" TEXT DEFAULT '#ffffff',
ADD COLUMN     "cardBackgroundGradient" BOOLEAN DEFAULT false,
ADD COLUMN     "cardBackgroundGradientColors" JSONB,
ADD COLUMN     "cardBackgroundGradientDirection" TEXT DEFAULT 'to right',
ADD COLUMN     "cardBorderColor" TEXT DEFAULT '#e5e7eb',
ADD COLUMN     "cardBorderRadius" INTEGER DEFAULT 8,
ADD COLUMN     "cardBorderWidth" INTEGER DEFAULT 1,
ADD COLUMN     "cardShadow" TEXT DEFAULT 'lg',
ADD COLUMN     "ctaButtonColor" TEXT DEFAULT '#007b5c',
ADD COLUMN     "ctaButtonColorGradient" BOOLEAN DEFAULT false,
ADD COLUMN     "ctaButtonColorGradientColors" JSONB,
ADD COLUMN     "ctaButtonColorGradientDirection" TEXT DEFAULT 'to right',
ADD COLUMN     "ctaText" TEXT DEFAULT 'Découvrir la boutique',
ADD COLUMN     "fontFamily" TEXT DEFAULT 'Inter',
ADD COLUMN     "fontSize" INTEGER DEFAULT 16,
ADD COLUMN     "fontWeight" TEXT DEFAULT 'normal',
ADD COLUMN     "logoUrl" TEXT,
ADD COLUMN     "miniCardBackgroundColor" TEXT DEFAULT '#ffffff',
ADD COLUMN     "miniCardBackgroundGradient" BOOLEAN DEFAULT false,
ADD COLUMN     "miniCardBackgroundGradientColors" JSONB,
ADD COLUMN     "miniCardBackgroundGradientDirection" TEXT DEFAULT 'to right',
ADD COLUMN     "miniCardBorderColor" TEXT DEFAULT '#e5e7eb',
ADD COLUMN     "miniCardBorderRadius" INTEGER DEFAULT 8,
ADD COLUMN     "miniCardBorderWidth" INTEGER DEFAULT 1,
ADD COLUMN     "miniCardShadow" TEXT DEFAULT 'md',
ADD COLUMN     "primaryColor" TEXT DEFAULT '#007b5c',
ADD COLUMN     "primaryColorGradient" BOOLEAN DEFAULT false,
ADD COLUMN     "primaryGradientColors" JSONB,
ADD COLUMN     "primaryGradientDirection" TEXT DEFAULT 'to right',
ADD COLUMN     "secondaryColor" TEXT DEFAULT '#ffffff',
ADD COLUMN     "secondaryColorGradient" BOOLEAN DEFAULT false,
ADD COLUMN     "secondaryGradientColors" JSONB,
ADD COLUMN     "secondaryGradientDirection" TEXT DEFAULT 'to right';
