-- AlterTable
ALTER TABLE "campaigns" ADD COLUMN     "backgroundColor" TEXT DEFAULT '#f8f9fa',
ADD COLUMN     "bannerUrl" TEXT,
ADD COLUMN     "budget" DOUBLE PRECISION,
ADD COLUMN     "conversionRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ctaButtonColor" TEXT DEFAULT '#007b5c',
ADD COLUMN     "ctaText" TEXT DEFAULT 'Découvrir les offres',
ADD COLUMN     "expectedROI" DOUBLE PRECISION,
ADD COLUMN     "facebookPixelId" TEXT,
ADD COLUMN     "featuredProducts" JSONB,
ADD COLUMN     "fontFamily" TEXT DEFAULT 'Inter',
ADD COLUMN     "googleAnalyticsId" TEXT,
ADD COLUMN     "klaviyoListId" TEXT,
ADD COLUMN     "logoUrl" TEXT,
ADD COLUMN     "mailchimpListId" TEXT,
ADD COLUMN     "mainOffer" TEXT,
ADD COLUMN     "primaryColor" TEXT DEFAULT '#007b5c',
ADD COLUMN     "secondaryColor" TEXT DEFAULT '#ffffff',
ADD COLUMN     "targetScans" INTEGER DEFAULT 1000,
ADD COLUMN     "targetSignups" INTEGER DEFAULT 200,
ADD COLUMN     "testimonials" JSONB,
ADD COLUMN     "totalScans" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalSignups" INTEGER NOT NULL DEFAULT 0;
